Feature/jc 602 page layout
saritasa-nest/camp-js-2024-ekaterina-tebyakina pull request #1
Opened 2024-07-04 08:53 UTC by TebyakinaEkaterina

Made the layout of the page

2024-07-05 10:12 UTC, SofyaKirillova requested changes

2024-07-05 10:12 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.css
> +  gap: 8px;
We have a variable for this

2024-07-05 10:12 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.css
> +    padding: 0 338px;
Can we round the value?

2024-07-05 10:12 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.css
> +    right: 338px;
Does this value have something to do with `padding`?

2024-07-05 10:12 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.html
> +								 class="form-field search-field">
Incorrect indents

2024-07-05 10:12 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.html
> +				<p class="logo">Books app <span class="copyright">© 2023</span></p>
```suggestion
				<p class="logo">Books app <span class="copyright">&copy; 2023</span></p>
```

2024-07-05 10:12 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.html
> +			<a href="#" class="top-link">Go to top ↑</a>
Let's use HTML-code or add an svg

2024-07-05 10:12 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.html
> +									 class="book-cover">
```suggestion
									alt="Book cover"
									class="book-cover">
```

Incorrect indents
Please, correct them in the entire file

2024-07-08 10:23 UTC, andrey-gazzaev approved these changes
Good job 👍

2024-07-08 10:23 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +          <input type="text"
```suggestion
          <input type="search"
```

2024-07-08 10:23 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +        <p class="filters__subtitle subtitle">Filters</p>
This is similar to the heading

2024-07-08 10:23 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +          <select name="sort-field"
Don't forget to add the label wrapper.
https://wiki.saritasa.rocks/frontend/languages/html#placeholders-as-labels-are-harmful

2024-07-08 10:23 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +          <p class="subsection__title subtitle">2020 Year</p>
Looks like the section doesn't have a heading

2024-07-08 10:23 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +            </div>
Usually the same content, like cards, is wrapped in articles

2024-07-08 10:23 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +        <a class="footer__contact-link">Github</a>
Let's add a title to the link

2024-07-09 06:39 UTC, SofyaKirillova approved these changes
Good job

2024-07-09 06:39 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +  --header-border-width: 1px;
It is unnecessary to create a separate variable for a value that is used once, if there are no questions when applying it

Also check out the other spaces

2024-07-09 06:39 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +  --footer-top-padding: 24px;
This variable is used in different places, it is better to put it in the `:host`

2024-07-09 06:39 UTC, SofyaKirillova commented on apps/vanilla/src/global/components.css
> +  /* background-image: url("./assets/icons/search.svg"); */
Delete the comment, please.

2024-07-09 08:01 UTC, karbik-creator approved these changes

2024-07-09 08:01 UTC, karbik-creator commented on apps/vanilla/src/global/components.css
> +  --subsection-item-gap: 8px;
The same. Reuse variables from `variables.css`

2024-07-09 08:01 UTC, karbik-creator commented on apps/vanilla/src/global/components.css
> +    --filters-form-gap-md: 32px;
The same. Reuse variables from variables.css

2024-07-09 08:06 UTC, karbik-creator requested changes
Let's fix display of large book title
![image](https://github.com/saritasa-nest/camp-js-2024-ekaterina-tebyakina/assets/63292584/dfb61a7c-52bf-41fe-9a54-b6cb444cbce4)

2024-07-09 09:21 UTC, TebyakinaEkaterina commented on apps/vanilla/src/global/components.css
> +  --subsection-gap: 16px;
Initially, I used global variables in the variables file like in your example, but I was advised to use local variables with a more semantic name. Or, if the value is used only in one place, do not specify it in the variable at all. What should I do in the end? Replace all local ones with global ones?

2024-07-09 10:41 UTC, TebyakinaEkaterina commented
> Let's fix display of large book title ![image](https://private-user-images.githubusercontent.com/63292584/346871023-dfb61a7c-52bf-41fe-9a54-b6cb444cbce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MjExOTQsIm5iZiI6MTcyMDUyMDg5NCwicGF0aCI6Ii82MzI5MjU4NC8zNDY4NzEwMjMtZGZiNjFhN2MtNTJiZi00MWZlLTlhNTQtYjZjYjQ0NGNiY2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEwMjgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNWEzYzE5NDc4NDBlYjUyNDkxZDZmNDZjN2MwYjRhODEyZjRkZTUyOTlhODY3NjM2NDc1NTY4YzM4NWVlYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uWmt9ILJbVvWIPDwHUHm3slmf-zcV-ucjqxUAAQqkDk)

I fixed it

2024-07-09 10:46 UTC, karbik-creator commented on apps/vanilla/src/global/components.css
> +  --subsection-gap: 16px;
These variables will still be useful to you, so let's add them right away

2024-07-09 10:55 UTC, karbik-creator requested changes

2024-07-09 10:55 UTC, karbik-creator commented on apps/vanilla/src/global/components.css
> +  max-height: 3rem;
Please check if these styles work correctly. An ellipsis should appear with large text

2024-07-09 12:21 UTC, karbik-creator approved these changes
Well done!

2024-07-09 13:02 UTC, merged