Feature/jc 632 blackjack by dice
saritasa-nest/camp-js-2024-ekaterina-tebyakina pull request #2
Opened 2024-07-11 09:19 UTC by TebyakinaEkaterina

Implemented a variant of the Blackjack game with a dice by using Observer pattern.

2024-07-12 04:51 UTC, khoanguyen-saritasa approved these changes
BTW, your code is really clean :) Nice job.

2024-07-12 04:51 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/index.html
> +			<a href="./task2/index.html" class="task-link" title="First task">Go to second task</a>
```suggestion
			<a href="./task2/index.html" class="task-link" title="Second task">Go to second task</a>
```

2024-07-12 04:51 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/task2/classes/displayers/player-result-displayer.ts
> +		this.layout.innerText = `${this.layout.innerText} ${String(playerResult.diceResult)}`;
```suggestion
		this.layout.innerText = `${this.layout.innerText} ${playerResult.diceResult.toString()}`;
```

2024-07-12 04:51 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/task2/classes/displayers/result-displayer.ts
> +		this.layout.innerText = `${this.layout.innerText} ${String(playerResult.diceResult)}`;
```suggestion
		this.layout.innerText = `${this.layout.innerText} ${playerResult.diceResult.toString()}`;
```

2024-07-12 04:51 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/task2/classes/publishers/dice-generator.ts
> + * TurnGenerator subscriber.
```suggestion
 * Turn generator subscriber.
```

2024-07-12 04:51 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/task2/classes/publishers/turn-generator.ts
> +	private calcCurrentPlayerIndex = (): void => {
```suggestion
	private calculateCurrentPlayerIndex = (): void => {
```
See: https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions

2024-07-12 04:51 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/task2/index.ts
> +const btn = document.querySelector('.button');
Can we rename this variable to something more specific?

2024-07-12 04:51 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/task2/classes/publishers/dice-generator.ts
> +	 * Generates a die roll and notifies a player of a result.
```suggestion
	 * Generates a dice roll and notifies a player of a result.
```

2024-07-12 07:17 UTC, dbitkovski requested changes

2024-07-12 07:17 UTC, dbitkovski commented on apps/vanilla/src/pages/task2/index.html
> +					<h2 class="container__header">Dice-cap</h2>
1. We don't have any styles for `container__header` (maybe they are in `"../../global/index.css"`?) so we can remove it
2. I guess this is a header of container__item and it's positioning depends on parent block, not a `container`

2024-07-12 07:17 UTC, dbitkovski commented on apps/vanilla/src/pages/task2/classes/publishers/turn-generator.ts
> +	private readonly playersCount: number = PLAYERS_COUNT;
Even though we have limitations of 2 people for a game we might pass players count as a parameter in constructor. Other parts of the class will remain the same but your implementation will be more flexible.

You can use `PLAYERS_COUNT` const as a default value

2024-07-12 07:17 UTC, dbitkovski commented on apps/vanilla/src/pages/task2/classes/publishers/publisher.ts
> +	public subscribe = (subscriber: Subscriber<T>): void	=> {
I can't get why you use arrow functions from time to time and mix it with "function decalration" approach :)
Do you need any of its functionality? I don't see `.subscribe` method is passed as a callback so there is not reason to think about context. And usually, even if we pass a method as callback, a class shouldn't know about it. We can easily wrap it to arrow function in place of execution.

In general I think we use function declaration for class methods so we can consider it as a company' practice. And also I can easily break your code right now because I can assign another implementation like this :)
`new Publisher().subscribe = () => console.log('Im sorry')`

2024-07-12 12:18 UTC, violetta-klintsova commented on apps/vanilla/src/pages/task2/core/publisher.ts
> + */
I don't quite see the point in this long docs, it's like you added some sort of a preview for class methods, but what for? You have docs for your methods inside

2024-07-12 12:18 UTC, violetta-klintsova commented on apps/vanilla/src/pages/task2/index.html
> +				<section class="container__item first-player-cap">
Do you use `first-player-cap` to apply some styles?

2024-07-12 12:18 UTC, violetta-klintsova commented on apps/vanilla/src/pages/task2/index.css
> +.diceRollButton {
I would be nice to stick to one type of case, I mean either kebab or camel
But I see that also use BEM, so I guess kebab is your choice

2024-07-12 12:18 UTC, violetta-klintsova commented on apps/vanilla/src/pages/task2/ui/player-result-displayer.ts
> +const BACKGROUND_COLOR = '#e0baba';
```suggestion
const WINNER_BACKGROUND_COLOR = '#e0baba';
```

2024-07-12 12:18 UTC, violetta-klintsova commented on apps/vanilla/src/pages/task2/ui/result-displayer.ts
> + */
```suggestion
/** Displays the received data. */
```

2024-07-12 12:25 UTC, violetta-klintsova commented on apps/vanilla/src/pages/task2/core/player.ts
> +	private checkIsWin(): void {
This is quite a friendly approach, everyone can be a winner :)
Do you have a requirement to stop the game once there's a winner though? If no, then I guess you could skip it, but it would be nice to disable dice rolls at this point

![image](https://github.com/user-attachments/assets/3e05e665-0f72-4efe-9b4c-78806317129c)

2024-07-15 03:02 UTC, TebyakinaEkaterina commented on apps/vanilla/src/pages/task2/index.html
> +				<section class="container__item first-player-cap">
No, but I use it to select this element in ts file by querySelector. Should I use id instead of class in this case?

2024-07-15 03:26 UTC, TebyakinaEkaterina commented on apps/vanilla/src/pages/task2/core/player.ts
> +	private checkIsWin(): void {
No, we do not have such a requirement

2024-07-15 08:51 UTC, violetta-klintsova commented on apps/vanilla/src/pages/task2/index.html
> +				<section class="container__item first-player-cap">
I thought of it, because classes is something that you may want to reuse, but IDs are supposed to be unique and they make sense in this case. It is not like you are going to have multiple players with the same name

2024-07-16 07:30 UTC, dbitkovski approved these changes

2024-07-16 08:19 UTC, merged