Feature/jc 644 initialize anime app
saritasa-nest/camp-js-2024-ekaterina-tebyakina pull request #3
Opened 2024-07-22 09:08 UTC by TebyakinaEkaterina

Create dashboard page with anime table.

2024-07-22 13:06 UTC, karbik-creator requested changes

2024-07-23 08:17 UTC, daoduong-saritasa requested changes

2024-07-23 08:17 UTC, daoduong-saritasa commented on apps/angular/src/app/features/dashboard/dashboard.component.ts
> +	protected readonly anime$ = this.animeApiService.getList();
Please review [this practice](https://wiki.saritasa.rocks/frontend/frameworks/angular/best-practices#do-not-subscribe-inside-a-constructor) from our wiki, `async pipe` section and it's look something like this
```suggestion
	protected readonly animeList$: Observable<Anime[]>;

	public constructor() {
		this.animeList$ = this.animeApiService.getList();
	}
```

2024-07-23 08:17 UTC, daoduong-saritasa commented on apps/angular/src/app/features/dashboard/dashboard.component.ts
> +	}
```suggestion
	protected trackByAnime(index: number, item: Anime): number {
		return item.id;
	}
```

2024-07-23 08:17 UTC, daoduong-saritasa commented on apps/angular/src/core/interceptors/api-key.interceptor.ts
> + * Adds header Api-Key to a request.
```suggestion
 * Add header Api-Key to a request.
```

2024-07-23 08:17 UTC, daoduong-saritasa commented on apps/angular/src/shared/pipes/empty.pipe.ts
> +		}
```suggestion
		const placeholderValue = placeholder ?? '\u2014';
```

2024-07-23 08:17 UTC, daoduong-saritasa commented on libs/core/dtos/anime.dto.ts
> +};
Consider this, would be more readable
```suggestion
export type AnimeDto = Readonly<{
	id: number;
	created: string;
	modified: string;
	title_eng: string;
	title_jpn: string;
	image: string;
	aired: AiredDto;
	type: AnimeTypeDto;
	status: AnimeStatusDto;
	score: number;
	user_score: number;
	studios: readonly number[];
  genres: readonly number[];
}>;

2024-07-23 08:17 UTC, daoduong-saritasa commented on libs/theme/src/variables.css
> +	--border-color: #00000026;
Why does it have 8 digit on a hex code?

2024-07-23 08:17 UTC, daoduong-saritasa commented on libs/core/models/anime.ts
> +// import { StatusModel } from '../dtos/anime.dto';
Please remove comment

2024-07-23 10:54 UTC, daoduong-saritasa commented on apps/angular/src/app/features/dashboard/dashboard.component.ts
> +	protected readonly anime$ = this.animeApiService.getList();
Hmm I don't know why this approach is outdated, the [angular docs](https://angular.dev/guide/pipes/unwrapping-data-observables) still use it to demo. I think this just personal choice, pick the one that suitable for you.

2024-07-23 11:12 UTC, TebyakinaEkaterina commented on apps/angular/src/app/features/dashboard/dashboard.component.ts
> +	protected readonly anime$ = this.animeApiService.getList();
Okay, thanks for the reply!

2024-07-24 12:25 UTC, karbik-creator requested changes

2024-07-24 12:25 UTC, karbik-creator commented on libs/core/dtos/anime.dto.ts
> +}
Let's create create separate files for `AnimeTypeDto`, `AnimeStatusDto`

2024-07-24 12:25 UTC, karbik-creator commented on libs/core/mappers/anime.mapper.ts
> +	}
Let's create create separate files for this mappers

2024-07-24 12:25 UTC, karbik-creator commented on apps/angular/src/core/services/anime-api.service.ts
> +			map(({ results }) => results.map((anime: AnimeDto) => AnimeMapper.fromDto(anime))),
```suggestion
			map(({ results }) => results.map(anime => AnimeMapper.fromDto(anime))),
```

2024-07-24 13:11 UTC, karbik-creator commented on apps/angular/src/app/features/dashboard/dashboard.component.html
> +			<ng-container matColumnDef={{columnsHeaders.AiredStart}}>
By task the image (reduced, should fit into the dimensions of 150x150px, but with the preservation of the original proportions). 
If I understand correctly, the image should be displayed like this
![image](https://github.com/user-attachments/assets/619efdf9-e7cb-4bc7-ad9a-084b631afa96)

But your implementation is different, please fix it
![image](https://github.com/user-attachments/assets/e51e5f77-7815-438e-b649-d6098dbfc8e3)

2024-07-25 05:55 UTC, TebyakinaEkaterina commented on apps/angular/src/environments/environment.ts
> +	apiKey: '4d114755-959f-4864-b484-b1752f9ae529',
Wouldn't it break the github deploy if the code in some files (e.g. interceptor) accesses a variable that wouldn't be available on github because it's in gitignore?

2024-07-25 08:49 UTC, karbik-creator commented on apps/angular/src/environments/environment.ts
> +	apiKey: '4d114755-959f-4864-b484-b1752f9ae529',
Yes, if we delete `apiKey `now, project will be deployed, but the data will not be displayed. Therefore, this comment is just for information, nothing needs to be changed

2024-07-25 08:54 UTC, TebyakinaEkaterina commented on apps/angular/src/environments/environment.ts
> +	apiKey: '4d114755-959f-4864-b484-b1752f9ae529',
Okay, thanks for information!

2024-07-25 08:54 UTC, karbik-creator approved these changes

2024-07-25 09:20 UTC, daoduong-saritasa approved these changes

2024-07-26 13:24 UTC, pavel-romanov8 requested changes

2024-07-26 13:24 UTC, pavel-romanov8 commented on libs/core/dtos/aired.dto.ts
> +export type AiredDto = Readonly<{
We try to stick with explicit declaration of read-only fields for each type/interfaces that we have in our projects.

2024-07-26 13:24 UTC, pavel-romanov8 commented on libs/core/mappers/anime-status.mapper.ts
> +	return AnimeStatus[enumKey];
With such approach we have this implicit connection between enum keys and we're forced to have the same keys for both enums. Otherwise this approach won't work.

I propose to declare mapping of enums more explicitly.

```typescript
const anumeStatusDtoMap: Readonly<Record<AnumeStatusDto, AnimeStatus>> = {
  [AnimeStatusDto.Movie]: AnimeStatus.Movie,
};
```

That we have have 0 coupuling and can be a lot more flexible in the way we write the code.

2024-07-26 13:24 UTC, pavel-romanov8 commented on libs/core/models/anime.ts
> +	public readonly type: string;
I believe we have a dedicated enum for anime type

2024-07-26 13:24 UTC, pavel-romanov8 commented on libs/core/mappers/anime-status.mapper.ts
> +export function fromStatusDto(status: AnimeStatusDto): AnimeStatus {
I'm not sure why you have decided to create a separate functions for status and type mapping, but for anime there is a dedicated namespace with function inside.

Let's be consistent and wrap these function in a dedicated namespace.

2024-07-26 13:24 UTC, pavel-romanov8 commented on apps/angular/src/app/features/dashboard/dashboard.component.html
> +						<img [src]="element.image"
For content images in Angular it is better to use `ngSrc` directive. You can read more about it [here](https://angular.dev/tutorials/learn-angular/11-optimizing-images#update-the-src-attribute-to-be-ngsrc)

2024-07-29 02:40 UTC, TebyakinaEkaterina commented on apps/angular/src/app/features/dashboard/dashboard.component.css
> +	white-space: nowrap;
I using them because I create an image's alt based on anime title. I thought that if the title was too long, the alt would be too long and the cell would stretch. So I applied the same styles to the cover as I did to the text cell. Is there a better approach to realize this?

2024-07-29 03:04 UTC, TebyakinaEkaterina commented on libs/core/dtos/aired.dto.ts
> +export type AiredDto = Readonly<{
You mean like this?
https://github.com/saritasa-nest/camp-js-2024-ekaterina-tebyakina/pull/3#discussion_r1687624457

2024-07-30 04:18 UTC, pavel-romanov8 approved these changes

2024-07-30 04:18 UTC, pavel-romanov8 commented on apps/angular/src/app/features/dashboard/dashboard.component.css
> +	white-space: nowrap;
In general, it does make sense to crop long titles to keep consistent UI, but we always provide an alternative for a user to see the full text when we're doing so.

For example, if we apply such text cropping to the anime title we should provide the `title` attribute where user can see the full title name if he hovers over it.
<img width="352" alt="Screenshot 2567-07-30 at 10 58 02" src="https://github.com/user-attachments/assets/fcafa35e-5129-43b8-9b8d-8ab9746d7027">

At this point we don't have it, but it is easy to fix and we can stay with text cropping. But we can't use `title` with image alt text, and there is no way for a user to see the full alt text.

2024-07-30 04:18 UTC, pavel-romanov8 commented on libs/core/dtos/aired.dto.ts
> +export type AiredDto = Readonly<{
Right

2024-07-30 04:18 UTC, pavel-romanov8 commented on libs/core/mappers/aired.mapper.ts
> +	export function fromAiredDto(aired: AiredDto): Aired {
Since we're using the mapper through the namespace there is no need to be that explicit with the function name.
```suggestion
	export function fromDto(aired: AiredDto): Aired {
```

Usage

```typescript
AiredMapper.fromDto(dto);
```

2024-07-30 06:27 UTC, TebyakinaEkaterina commented on apps/angular/src/app/features/dashboard/dashboard.component.css
> +	white-space: nowrap;
Got it! Thanks for the explanation

2024-07-30 07:09 UTC, merged