Feature/JC-660 | Anime list management
saritasa-nest/camp-js-2024-ekaterina-tebyakina pull request #4
Opened 2024-07-31 05:32 UTC by TebyakinaEkaterina

Implement pagination, filtering and sorting for the anime table.

2024-08-01 04:29 UTC, shalomich requested changes

2024-08-01 04:29 UTC, shalomich commented on apps/angular/src/app/features/dashboard/dashboard.component.ts
> +		this.subs.push(this.animeParams$.subscribe(params => {
It's cool that you subscribe to `animeParams$` in template using `async` pipe. Thus this subscription looks redudant

2024-08-01 04:29 UTC, shalomich commented on apps/angular/src/app/features/filter-form/filter-form.component.ts
> +		term: new FormControl(''),
Why not have one `FormGroup` for both `search` and `animeType`?

2024-08-01 04:29 UTC, shalomich commented on apps/angular/src/app/features/filter-form/filter-form.component.ts
> +		term: new FormControl(''),
Please use `NonNullableFormBuilder` to create both `FormGroup` and `FormControl`. Ideally do it in separate method:
`private initializeAnimeFiltersForm(): FormGroup<AnimeFilterFormControls>`

2024-08-01 04:29 UTC, shalomich commented on apps/angular/src/app/features/filter-form/filter-form.component.ts
> +	protected onSearchSubmit(): void {
Please use `formGroup.valueChanges` to subscirbe form changes instead it

2024-08-01 04:29 UTC, shalomich commented on libs/core/models/query-params.ts
> +	ordering: AnimeSort;
```suggestion
	readonly offset: number;

	/** Limit. */
	readonly limit: number;

	/** Search. */
	readonly search: string;

	/** Type. */
	readonly type: AnimeType[];

	/** Ordering. */
	readonly ordering: AnimeSort;
```

2024-08-01 04:29 UTC, shalomich commented on libs/core/models/query-params.ts
> +export type QueryParams = {
Please use the prefix of model, because theoretically these may not be the only query parameters in the application.

```suggestion
export type AnimeQueryParams = {
```

2024-08-01 04:29 UTC, shalomich commented on libs/core/models/columns-indexes.ts
> +export enum ColumnsIndexes {
```suggestion
export enum AnimeColumnsIndexes {
```

2024-08-01 04:29 UTC, shalomich commented on libs/core/models/columns-headers.ts
> +export enum ColumnsHeaders {
```suggestion
export enum AnimeColumnsHeaders {
```

2024-08-01 04:29 UTC, shalomich commented on libs/core/mappers/query-params.mapper.ts
> +			limit: 25,
Please use constants for default values

2024-08-01 04:29 UTC, shalomich commented on libs/core/mappers/query-params.mapper.ts
> +		}
An example for `offset` how it can be simplified

```suggestion
		const queryParams: QueryParams = {
			offset: params.offset ? params.offset : DEFAULT_OFFSET,
                }
```

2024-08-01 04:29 UTC, shalomich commented on libs/core/mappers/query-params.mapper.ts
> +			queryParams.offset = params.offset;
What if `offset` or `limit` is not number or less than zero?

2024-08-01 04:29 UTC, shalomich commented on libs/core/mappers/query-params.mapper.ts
> +		return queryParams;
```suggestion
		const types = params.type.map(animeType => AnimeTypeMapper.toDto(animeType)).join(',');
		const ordering = AnimeSortMapper.toDto(params.ordering);

		return  {
			offset,
			limit,
			search,
			ordering,
			type_in: types,
		};
```

2024-08-01 04:29 UTC, shalomich commented on libs/core/mappers/pagination.mapper.ts
> +	export function fromDto<I, O>(pagination: PaginationDto<I>, mapper: (dto: I) => O): Pagination<O> {
Please use correct name for generic parameters
```suggestion
	export function fromDto<TDto, TModel>(pagination: PaginationDto<TDto>, mapper: (dto: TDto) => TModel): Pagination<TModel> {
```

2024-08-01 04:29 UTC, shalomich commented on libs/core/dtos/query-params.dto.ts
> +	ordering?: string;
```suggestion
	readonly type__in?: string;

	/** Ordering. */
	readonly ordering?: string;
```

2024-08-01 04:29 UTC, shalomich commented on apps/angular/src/core/services/anime-api.service.ts
> +		const pageParams = new HttpParams()
Please use `new HttpParams({ fromObject: { ... }})`

2024-08-01 04:29 UTC, shalomich commented on apps/angular/src/core/services/anime-api.service.ts
> +		return this.http.get<PaginationDto<AnimeDto>>('anime/anime/', {
Please use separate service for URL config

2024-08-01 04:29 UTC, shalomich commented on apps/angular/src/app/features/table/table.component.ts
> +	@Input() public offset = 0;
Your default values are repeated in several places

2024-08-01 04:29 UTC, shalomich commented on apps/angular/src/app/features/table/table.component.ts
> +	@Input() public ordering?: Sort;
Please don't use angluar `Sort`. You need to have own model for this.

2024-08-01 04:29 UTC, shalomich commented on apps/angular/src/app/features/table/table.component.ts
> +export class TableComponent implements OnInit {
```suggestion
export class AnimeTableComponent implements OnInit {
```

2024-08-01 04:29 UTC, shalomich commented on apps/angular/src/app/features/table/table.component.html
> +									 [pageSizeOptions]="[10, 25, 50]"
Please have constant in component

2024-08-05 04:35 UTC, shalomich approved these changes
Good work!

2024-08-05 04:35 UTC, shalomich commented on libs/core/mappers/anime-sort.mapper.ts
> +		if (value === 'asc' || value === 'desc' || value === '') {
It is not good that you compare `string` with literals. Perhaps you can create enum for `SortDirection`

```
enum SortingDirection {
	Ascending = 'asc',
	Descending = 'desc',
        None = ''
}
```

2024-08-05 04:35 UTC, shalomich commented on libs/core/mappers/anime-sort.mapper.ts
> +		return sortSettingsString;
```suggestion
		return sortSettings ? `${sortField},${direction}` : '';
```

2024-08-05 04:35 UTC, shalomich commented on libs/core/mappers/anime-sort.mapper.ts
> +		return orderString;
```suggestion
		const {sortField, direction } = ordering;
		
		if (direction === '') {
		   return '';
		}
		
		return direction === 'asc' : sortField : `-${sortField}`;
```

2024-08-05 04:35 UTC, shalomich commented on libs/core/mappers/anime-sort.mapper.ts
> +		if (ordering[0] === '-') {
Please use constant for '-', for example `DesceningPreffix`

2024-08-05 04:35 UTC, shalomich commented on apps/angular/src/core/services/url-config.service.ts
> +	};
The name of the object means that all endpoints will be contained here. But for a large number of endpoints, this is inconvenient. It is better to create an object for each endpoint group. For example, now we have an `anime` group, but we can have an `auth` group to log in and register.

```suggestion
	public readonly anime = {
		getList: 'anime/anime/',
	};
```

2024-08-05 04:35 UTC, shalomich commented on libs/core/models/anime-filter-params.ts
> +export type AnimeFilterParams = {
I would name it `AnimeParams` or `AnimeFetchParams`. I would have `AnimeFilterParams` only for `searchTerm` and `selectedTypes`

2024-08-05 04:35 UTC, shalomich commented on apps/angular/src/app/features/dashboard/dashboard.component.ts
> +	}
```suggestion
	private navigate(params: Partial<AnimeFilterParams>): void {
		this.router.navigate(
			[''],
			{
				queryParams: AnimeQueryParamsMapper.toQueryParams(params),
				queryParamsHandling: 'merge',
			},
		);
	}
```

2024-08-05 05:12 UTC, daoduong-saritasa commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.component.ts
> +	public constructor(private readonly formBuilder: NonNullableFormBuilder) {}
Prefer using `inject` to inject dependencies rather than constructor injections

2024-08-05 05:17 UTC, daoduong-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +			<ng-container matColumnDef={{columnsIndexes.Image}}>
`Indexes` here is abundant, `columns.Image` is enough meaning

2024-08-05 05:24 UTC, daoduong-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	protected onPageChanged(event: PageEvent): void {
I think present tense is fine, otherwise you have to update the functions name to past tense also. Ex: `onDataSorted`
```suggestion
	protected onPageChange(event: PageEvent): void {
```

2024-08-05 05:40 UTC, daoduong-saritasa commented on libs/core/mappers/anime-type.mapper.ts
> +	const animeTypeMap: Readonly<Record<AnimeType, AnimeTypeDto>> = {
```suggestion
	const ANIME_TYPE_MAP_TO_DTO: Readonly<Record<AnimeType, AnimeTypeDto>> = {
```

2024-08-05 05:42 UTC, daoduong-saritasa commented on libs/core/models/anime-sort.ts
> +/** */
Missing docs

2024-08-05 07:31 UTC, TebyakinaEkaterina commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +								 [alt]="element.japaneseTitle ? element.japaneseTitle + ' cover' : 'Anime cover'"
This causes an error
![Screenshot from 2024-08-05 14-30-47](https://github.com/user-attachments/assets/3cf29492-31c0-4b62-9178-c89e9ebef3e1)

2024-08-05 07:42 UTC, daoduong-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +								 [alt]="element.japaneseTitle ? element.japaneseTitle + ' cover' : 'Anime cover'"
Sorry, my bad, I forgot that we can't do like that in template, please try this
`[alt]="(element.japaneseTitle ?? 'Anime') + ' cover'"`

2024-08-05 08:38 UTC, TebyakinaEkaterina commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +								 [alt]="element.japaneseTitle ? element.japaneseTitle + ' cover' : 'Anime cover'"
It works, thanks!

2024-08-05 09:13 UTC, TebyakinaEkaterina commented on libs/core/models/anime-columns-indexes.ts
> +}
Yeah, you got that right. I added the dto and the mapper now, thanks for the advice!

2024-08-05 09:54 UTC, daoduong-saritasa approved these changes

2024-08-05 09:54 UTC, daoduong-saritasa commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.component.ts
> +	protected readonly typesList = Object.values(AnimeType);
You don't need to add `List` if that word is already plural and the naming can improve a bit 
```suggestion
	protected readonly animeTypes = Object.values(AnimeType);
```

2024-08-05 09:54 UTC, daoduong-saritasa commented on libs/core/mappers/anime-status.mapper.ts
> +	const ANIME_STATUS_MAP_TO_DTO: Readonly<Record<AnimeStatusDto, AnimeStatus>> = {
This should be `...FROM_DTO`

2024-08-07 03:36 UTC, pavel-romanov8 requested changes
Before going deep into code review, let's work on the overall app functionality.

1. We show the loader only on the initial load. Whenever a user change filters or pagination configuration we're not showing it. It is especially noticeable with slow internet connection.

https://github.com/user-attachments/assets/c6c4bb89-9fc1-42ea-b48a-d131a975b5a4

2. I see that we have logic to reset the page number whenever filters change, but we're not doing so when page size changes. It leads to confusing UX.

https://github.com/user-attachments/assets/8fac8660-af0f-44a7-9da6-d3f2fe114b6a

3. When I try to navigate to a previous page, it doesn't work.

https://github.com/user-attachments/assets/76fd53c1-c11d-478f-8e25-62c1f2290f21

4. When I change page size I want to see the number of total pages reflect the changes, but they stay the same. Only if I reload the page then I can see different number of pages.

https://github.com/user-attachments/assets/d6a490b5-5534-4317-8546-54756f3caf9b

2024-08-07 08:38 UTC, TebyakinaEkaterina commented
Fixed it!
> Before going deep into code review, let's work on the overall app functionality.
> 
> 1. We show the loader only on the initial load. Whenever a user change filters or pagination configuration we're not showing it. It is especially noticeable with slow internet connection.
> 
>  Screen.Recording.2567-08-07.at.10.17.22.mov 
> 2. I see that we have logic to reset the page number whenever filters change, but we're not doing so when page size changes. It leads to confusing UX.
> 
>  Screen.Recording.2567-08-07.at.10.13.49.mov 
> 3. When I try to navigate to a previous page, it doesn't work.
> 
>  Screen.Recording.2567-08-07.at.10.10.32.mov 
> 4. When I change page size I want to see the number of total pages reflect the changes, but they stay the same. Only if I reload the page then I can see different number of pages.
> 
>  Screen.Recording.2567-08-07.at.10.07.16.mov

2024-08-09 03:25 UTC, TebyakinaEkaterina commented
> Before going deep into code review, let's work on the overall app functionality.
> 
> 1. We show the loader only on the initial load. Whenever a user change filters or pagination configuration we're not showing it. It is especially noticeable with slow internet connection.
> 
>  Screen.Recording.2567-08-07.at.10.17.22.mov 
> 2. I see that we have logic to reset the page number whenever filters change, but we're not doing so when page size changes. It leads to confusing UX.
> 
>  Screen.Recording.2567-08-07.at.10.13.49.mov 
> 3. When I try to navigate to a previous page, it doesn't work.
> 
>  Screen.Recording.2567-08-07.at.10.10.32.mov 
> 4. When I change page size I want to see the number of total pages reflect the changes, but they stay the same. Only if I reload the page then I can see different number of pages.
> 
>  Screen.Recording.2567-08-07.at.10.07.16.mov

Regarding point 4 - it's always one number there now (unless the anime list is filtered), because that's the number of anime that shouldn't change when the page size changes. I did it wrong at first by putting the number of pages there

2024-08-12 04:01 UTC, pavel-romanov8 requested changes
We still have the issue where number of available pages isn't refreshing after changing page size


https://github.com/user-attachments/assets/635601f7-1847-49ab-8541-8f8b0a2fc291

2024-08-12 11:28 UTC, pavel-romanov8 requested changes

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.component.html
> +<div class="filter-form-wrapper">
From what I see, we're not utilizing this class in any way

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.component.html
> +	@if (animeFilterFormGroup) {
This `if` block looks redundant because `animeFilterFormGroup` is non-nullable and always presented in the component

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.component.html
> +						[formControl]="animeFilterFormGroup.controls.search"/>
We usually place closing part on a new line to make it more clear where the list of attributes ends
```suggestion
					<input
						matInput
						placeholder="Type to Search"
						class="search-form__input"
						type="search"
						[formControl]="animeFilterFormGroup.controls.search"
				  />
```

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.component.html
> +<div class="filter-form-wrapper">
Do we even need this `div`?

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.component.css
> +	--button-margin-bottom: 20px;
Please, try to position elements from the parent elements, that way we make our components more reusable and modular

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.component.ts
> +	public animeFiltersEvent = new EventEmitter<AnimeFilters>();
You can keep outputs read-only because we're not changing it at any given point in time
```suggestion
	public readonly animeFiltersEvent = new EventEmitter<AnimeFilters>();
```

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.component.ts
> +		const isPartial = !(filters && 'search' in filters && 'types' in filters);
I would try to avoid `in` operator as much as possible, because it is not type-safe. Sure, it works for type narrowing well. It also works in runtime, but if we decide to change `types` to `type` we won't get any error here.

What you can do instead is to use type assertion (it is one of the few places where it is worth using it).
```typescript
function isAnimeFilter(value: unknown): asserts value is AnimeFilter {
  const filter = value as AnimeFilter;
  return filter.search != null && filter.types != null;
}
```

If we decide to change anything inside of `AnimeFilter` there will be a typescript error.

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.service.ts
> +export type AnimeFilterFormParams = {
From what I see we're not using this type only inside this file, and there is no need to export it

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.service.ts
> +export type UpdateControlsValuesParams = {
The same thing with exported type, it is redundant in this case

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-filter-form/anime-filter-form.service.ts
> +export type AnimeFilterForm = {
What do you think about moving form itself into this service? That way, we can further encapsulate the related logic, keep this type local, with no need to export it, and avoid a bit of strange injection of form in `updateControlsValues` just to update the values.

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	public pageData?: Pagination<Anime>;
If this field is required, there is no way it can be optional, right? I believe that you did it this way for a simple reason - ESLint.

What we usually do in such cases is explicitly initialize this field with `null.` That way, there is no need to have optional fields, and we don't have to deal with `undefined`.

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	public sortEvent = new EventEmitter<Sort>();
Let's turn those outputs into read-only outputs

2024-08-12 11:28 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +				<mat-cell
```suggestion
					  *matHeaderCellDef
					  class="table__title"
					>
					  {{columnsHeaders.Image}}
					</mat-header-cell>
				<mat-cell
```

2024-08-12 11:28 UTC, pavel-romanov8 commented on libs/core/dtos/anime-params.dto.ts
> +	/** Limit. */
Looks like documentation for `offset` and `limit` is mixed up

2024-08-12 11:28 UTC, pavel-romanov8 commented on libs/core/mappers/anime-query-params.mapper.ts
> +			selectedTypes = typesArray.filter(item => checkIsEnumMember(item, AnimeType)) as AnimeType[];
To avoid using `as` you can provide an explicit type guard for filter callback function (it works well without it only starting from typescript 5.5).
```typescript
selectedTypes = typesArray.filter((item): item is AnimeIndexType => checkIsEnumMember(item, AnimeType));
```

2024-08-12 11:28 UTC, pavel-romanov8 commented on libs/core/tsconfig.app.json
> +  "include": ["**/*.ts", "models/anime-query-params.ts"]
Can you please provide some context on why do we need to change the tsconfig in this case?

2024-08-13 02:58 UTC, TebyakinaEkaterina commented on apps/angular/src/app/features/anime-dashboard/anime-dashboard.component.html
> +			<camp-progress-bar/>
I wanted the loader to be displayed directly above the table, but I've rearranged it now

2024-08-13 04:44 UTC, pavel-romanov8 approved these changes
The code looks tidy, and the workflow is clear. Nice job 👍

2024-08-13 04:44 UTC, pavel-romanov8 commented on libs/core/models/anime-filters.ts
> +	types: AnimeType[];
Are those fields mutable? If not, we can declare them as read-only

2024-08-13 05:05 UTC, merged