Jc 679 authorization feature
saritasa-nest/camp-js-2024-ekaterina-tebyakina pull request #6
Opened 2024-08-13 09:57 UTC by TebyakinaEkaterina

Implementation of authorization and registration

2024-08-16 06:57 UTC, karbik-creator requested changes

2024-08-16 06:57 UTC, karbik-creator commented on apps/angular/src/app/features/login-form/login-form.component.html
> +					<mat-error>Enter a valid email address.</mat-error>
Getting an error and checking touched control is repeated many times. Let's try to move this logic into a reusable function or method

2024-08-16 06:57 UTC, karbik-creator commented on apps/angular/src/app/features/login-form/login-form.component.html
> +				[disabled]="loginFormService.form.invalid"
Disabling a button is bad practice. You can read about it here https://www.smashingmagazine.com/2021/08/frustrating-design-patterns-disabled-buttons/#the-downsides-of-disabled-buttons
So let's remove this attribute and add a validity check to submit method

2024-08-16 06:57 UTC, karbik-creator commented on apps/angular/src/app/features/authorization-menu/authorization-menu.component.ts
> +	public readonly user$: BehaviorSubject<User | null> = new BehaviorSubject<User | null>(null);
```suggestion
	public readonly user$ = new BehaviorSubject<User | null>(null);
```

2024-08-16 06:57 UTC, karbik-creator commented on apps/angular/src/app/features/login-form/login-form.component.ts
> +			}),
We usually don't use `next`, `error`. Let's change it to `catchError `and `tap`
```
catchError((error: unknown) => ...),
tap(() => ...),
```

2024-08-19 06:46 UTC, karbik-creator commented on apps/angular/src/core/services/authorization-api.service.ts
> +			catchError((error: unknown) => throwError(() => error)),
Let's improve this code a little
```suggestion
			switchMap(refreshToken => {
				if (refreshToken) {
					return this.http.post<AuthorizationTokensDto>(this.urlConfigService.authorization.refresh,
						{ refresh: refreshToken });
				}
				return throwError(() => new Error('Failed to refresh token'));
			}),
			map(response => AuthorizationTokensMapper.fromDto(response)),
			tap(response => this.localStorageService.saveTokens(response)),
```

2024-08-19 06:46 UTC, karbik-creator commented on apps/angular/src/core/services/users-api.service.ts
> +				if (JSON.stringify(result) === JSON.stringify(this.errorObject)) {
let's add a comment why this check was added here and not in `catchError`

2024-08-19 06:46 UTC, karbik-creator commented on apps/angular/src/core/utils/compare-form-fields.util.ts
> +	return (formGroup: AbstractControl): { [key: string]: unknown; } | null => {
```suggestion
	return (formGroup: AbstractControl): ValidationErrors | null => {
```

2024-08-19 06:46 UTC, karbik-creator commented on apps/angular/src/core/utils/compare-form-fields.util.ts
> +	return (formGroup: AbstractControl): { [key: string]: unknown; } | null => {
Although I see that this method only returns null. Let's try to remake the validator so that we don't have to reset the error and install it ourselves. Think about how you can bind the validator to the control itself, not to the form

2024-08-19 07:23 UTC, khoanguyen-saritasa requested changes
It seems like the refresh token function isn't working as expected. I'm encountering an infinite loop of refreshing tokens when the refresh token is invalid. You can check the video below for a reproduction of the issue.
[Screencast from 19-08-2024 14:20:22.webm](https://github.com/user-attachments/assets/d95db8e9-c29e-41d4-bb0c-d952eb3d1da8)
Please also handle the case for invalid refresh token as well. If you have any question, you can ping me.

2024-08-19 07:23 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/authorization-menu/authorization-menu.component.ts
> +	public readonly user$: BehaviorSubject<User | null> = new BehaviorSubject<User | null>(null);
It seems to me that you should store the user variable in a reusable service. What if we need to check for user role or something that need to have the user information in another component?

2024-08-19 07:23 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/authorization-menu/authorization-menu.component.ts
> +		this.updateUser();
Let's separate these side effects into functions, so you only need to subscribe to them as one in the merged sources. For example:
```typescript
merge(this.yourSideEffectFn(), this.yourSecondSideEffectFn()).pipe(takeUntilDestroy(this.destroyRef)).subcribe()
``` 
This way, your ngOnInit will be cleaner, and you'll only need to subscribe and destroy it once.

2024-08-19 07:23 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/authorization-menu/authorization-menu.component.ts
> +	}
Let's use `catchError` operator for catching error.

2024-08-19 07:23 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/registration-form/registration-form.service.ts
> +	readonly retypedPassword: FormControl<string>;
Let's avoid duplicating context. Since this is declared as a type, it can simply be the type. You can omit the prefix **Type of form control**.

2024-08-19 07:23 UTC, khoanguyen-saritasa commented on libs/core/models/user.ts
> +	public readonly modified: Date;
Let's avoid context duplicate. We don't need `User's` as a prefix of docs.

2024-08-26 08:03 UTC, daoduong-saritasa requested changes

2024-08-26 08:03 UTC, daoduong-saritasa commented on libs/core/dtos/server-error-attribute.dto.ts
> +export enum ServerErrorAttributeDto {
Missing docs

2024-08-26 08:03 UTC, daoduong-saritasa commented on libs/core/mappers/authorization-tokens.mapper.ts
> +export namespace AuthorizationTokensMapper {
Missing docs. And please update for remaining `.mapper` files also. I saw multiple of them are missing docs

2024-08-26 08:03 UTC, daoduong-saritasa commented on libs/core/models/server-error-status.ts
> +export enum ServerErrorStatus {
`@angular/common/http` has `HttpStatusCode` which serve the same purpose

2024-08-26 08:03 UTC, daoduong-saritasa commented on libs/core/dtos/user.dto.ts
> +export type UserDto = {
Missing docs

2024-08-26 10:52 UTC, TebyakinaEkaterina commented on apps/angular/src/app/features/login-form/login-form.service.ts
> +	public readonly form: FormGroup<LoginForm>;
In the last task, I had a similar situation and Pavel advised me to move the form to the service. What should I do?
https://github.com/saritasa-nest/camp-js-2024-ekaterina-tebyakina/pull/4#discussion_r1713564734

2024-08-26 11:59 UTC, karbik-creator commented on apps/angular/src/app/features/login-form/login-form.service.ts
> +	public readonly form: FormGroup<LoginForm>;
okay, let's leave Pavel's suggested option

2024-08-28 04:14 UTC, daoduong-saritasa approved these changes

2024-08-28 04:14 UTC, daoduong-saritasa commented on apps/angular/src/core/services/local-storage-for-authorization.service.ts
> +		this.localStorageService.setValue('refreshToken', tokens.refresh);
I saw `accessToken` and `refreshToken` use a lot, consider create an enum for it.

2024-08-28 04:14 UTC, daoduong-saritasa commented on apps/angular/src/core/services/local-storage-for-authorization.service.ts
> +	}
If we have enum for token keys, these functions can be remove and the usage from other services would be something like `LocalStorageService.get(TokenKey.Access)`

2024-08-28 04:14 UTC, daoduong-saritasa commented on apps/angular/src/core/services/local-storage.service.ts
> +	public setValue<T>(name: string, value: T): void {
We can remove `Value` here, it doesn't provide any meaning. `LocalStorageService` with `get` `set` and `remove` is enough meaning

2024-08-29 11:37 UTC, khoanguyen-saritasa approved these changes

2025-03-25 04:04 UTC, closed without merging