Feature/jc 702 initialize anime app
saritasa-nest/camp-js-2024-ekaterina-tebyakina pull request #8
Opened 2024-08-15 10:11 UTC by TebyakinaEkaterina

Implement base layout for React solution.

2024-08-16 03:31 UTC, shalomich approved these changes

2024-08-16 03:31 UTC, shalomich commented on apps/react/src/features/anime/pages/AnimePage.tsx
> +export const AnimePage = memo(AnimePageComponent);
```suggestion
/** Memorized anime page component. */
export const AnimePage = memo(AnimePageComponent);
```

2024-08-16 03:31 UTC, shalomich commented on apps/react/src/features/anime/routes.tsx
> +		element: <Navigate to="AnimePage" />,
Does it work?

```suggestion
		element: <Navigate to="anime" />,
```

2024-08-16 03:31 UTC, shalomich commented on apps/react/src/features/genres/components/GenresFilterForm/GenresFilterForm.tsx
> + */
Please prefer one-line comments for methods without parameters

```suggestion

/** Memorized filter form. */
```

2024-08-16 03:31 UTC, shalomich commented on apps/react/src/features/genres/components/GenresList/GenresList.module.css
> +	padding-top: 0 !important;
Why do you need `!important` here?

2024-08-16 03:31 UTC, shalomich commented on apps/react/src/features/genres/components/GenresList/GenresList.tsx
> +				to={`/genres/${genre.id}`}
Let's have constants for paths in `routes.tsx` files to reuse it instead of using literals here.

2024-08-16 03:31 UTC, shalomich commented on apps/react/src/features/genres/pages/GenresPage/GenresPage.module.css
> +.main__section__list {
You can't have `BEM-element` of `BEM-element`
```suggestion
.main__section-list {
```

2024-08-16 03:31 UTC, shalomich commented on apps/react/src/features/genres/pages/GenresPage/GenresPage.tsx
> +			</Box>
If you don't need to use the Box features, it's better to use a div

```suggestion
			<div className={styles.main__section}>
				<GenresFilterForm/>
				<div className={styles.main__section__list}>
					<GenresList genres={genres} />
				</div>
			</div>
			<div className={styles.main__details}>
				<Outlet />
			</div>
```

2024-08-16 03:31 UTC, shalomich commented on apps/react/src/features/genres/pages/GenresPage/GenresPage.tsx
> +				</Box>
Do we really need this wrapper? Can we do that?
```suggestion
				<GenresList genres={genres}  className={styles.main__section__list}/>
				
```

2024-08-16 03:31 UTC, shalomich commented on apps/react/src/features/genres/components/GenreCard/GenreCard.tsx
> +	const linkToEdit = `${location.pathname}/edit`;
Configuring it this way is an unreliable solution. If I change the paths in `routes.tsx`, a bug will occur. To do this, have a constant in `routes.ts` to reuse here

2024-08-16 03:31 UTC, shalomich commented on apps/react/src/components/header/Header.tsx
> +			<Box>Authorization menu</Box>
```suggestion
			<span>Authorization menu</span>
```

2024-08-16 03:31 UTC, shalomich commented on apps/react/src/components/header/Header.tsx
> +	const isActive = (path: string) => location.pathname.startsWith(path);
```suggestion
	const isCurrentPath = (path: string) => location.pathname.startsWith(path);
```

2024-08-16 03:37 UTC, shalomich commented
@TebyakinaEkaterina Please give your commits more specific names. I do not recommend calling them "Refactoring code", because sometimes it is necessary to go back through the commit history, for example, to find when a bug appeared, and such commit messages do not help in any way

2024-08-16 06:52 UTC, TebyakinaEkaterina commented on apps/react/src/features/genres/components/GenresList/GenresList.module.css
> +	padding-top: 0 !important;
I use it to remove default material padding

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa requested changes

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/components/header/Header.module.css
> +	flex-direction: row !important;
We should avoid using `!improtant` if possible. CSS modules are not the default solution for styling MUI components, so you need to tweak MUI a bit to reduce specificity of inner MUI styles. Follow this guide:
https://mui.com/material-ui/integrations/interoperability/#css-modules

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/components/header/Header.module.css
There is no benefit to use BEM with isolated styles. In most new project, we prefer to simple class names like `.header, .title, .nav`.
I personally think, you got enough experience with BEM in angular part.

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/components/header/Header.tsx
> +/** Memorized header. */
Not sure if it's just a typo. 
But still, `memo` used to **memoize** component. Memorization and memoization are two different terms.

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/components/header/index.ts
Barrel files are considered a bad practice. You can read this https://laniewski.me/blog/pitfalls-of-barrel-files-in-javascript-modules/ or any other similar article.

We probably have barrel files in boilerplate, it's pretty old tho, so give as some slack here =]

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/routes.tsx
> +export const animeRoutes: RouteObject[] = [
```suggestion
export const animeRoutes: readonly RouteObject[] = [
```

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/routes.tsx
> +/** Route object for AnimePage. */
Don't use variable names in description.

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/routes.tsx
> +/** Route object for AnimePage. */
To properly reference entities from codebase, you can use `{@linkcode AnimePage}`, but I don't think you need it here.

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/genres/components/GenresList/GenresList.module.css
> +	padding-top: 0 !important;
You won't need it after updating MUI styles provision configuration

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/genres/components/GenresList/GenresList.module.css
> +	cursor: pointer;
`cursor: pointer` usually placed inside just class without pseudo selectors. It can feel counterintuitive at first, but it works this way.

```suggestion
.list__item {
	border: 1px var(--border-color) solid;
	color: var(--primary-font-color);
  cursor: pointer;
}

.list__item:hover,
.list__item:focus {
```

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/genres/components/GenresList/GenresList.tsx
> +	readonly genres: Genre[];
```suggestion
	readonly genres: readonly Genre[];
```

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/genres/components/GenresList/GenresList.tsx
> +const GenresListComponent: FC<Props> = ({ genres }: Props) => (
You can omit function argument type annotation when using `FC<Props>`
```suggestion
const GenresListComponent: FC<Props> = ({ genres }) => (
```

2024-08-16 11:43 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/genres/routes.tsx
> +export const PATH_TO_EDIT_GENRE = 'edit';
What do you think about simplify naming by remove `TO`? `GENRES_PATH` for example.

2024-08-19 04:35 UTC, TebyakinaEkaterina commented on apps/react/src/features/genres/components/GenresList/GenresList.tsx
> +const GenresListComponent: FC<Props> = ({ genres }: Props) => (
Lint notifies of an error if we omit this type annotation

2024-08-19 08:01 UTC, artem-sotnichenko-saritasa approved these changes

2025-03-25 04:05 UTC, closed without merging